#!/bin/bash

set -a

if [ -f "local.env" ]; then 
    source local.env
fi

# This script is intended to be a common entrypoint for managing this environment.
export MSYS_NO_PATHCONV=1
set -e

# =================================================================================================================
# Usage:
# -----------------------------------------------------------------------------------------------------------------
usage() {
    cat <<-EOF

        Usage: $0 [command] [options]

        Commands:

        setup - Copy properties files to volumes
                Create Oscar instance
                Boostrap the db with initial oscar db
                
                Examples:
                - Setup OpenOSP environment.
        
                    $0 setup

        bootstrap - Make a new, empty db

        purge - Delete OSCAR related files
                Drop current databse.

        backup - Trigger Backups, by default, will run the auto backup container
                Examples:
                - Run automated backups.
                    $0 backup
                - Run manual backups.
                    $0 backup -m

        build - to build the oscar source WAR and docker image

        publish - to push to dockerhub

        update - to update the openosp docker image

        start - to bring up containers if needed.

EOF
    exit 1
}

toLower() {
    echo $(echo ${@} | tr '[:upper:]' '[:lower:]')
}

#=============================================================================


COMMAND=$(toLower ${1})

case "${COMMAND}" in
    setup)
        ./bin/openosp-setup.sh $2 $3
        ;;
    purge)
        ./bin/openosp-purge.sh $2 $3
        ;;
    start)
       ./bin/openosp-start.sh $2 $3
        ;;
    backup)
        if  [[ $2 = "-m" ]]; then
            echo "Manually Backing up files"
            ./bin/openosp-backup.sh
        else
            echo "Running Auto backups"
            ./bin/run-auto-backups.sh
        fi
        ;;
    build)
        ./bin/openosp-build.sh $2 $3
        ;;
    publish)
        ./bin/openosp-publish.sh $2 $3
        ;;
    bootstrap)
        ./bin/openosp-bootstrap.sh $2 $3
        ;;
    update)
        ./bin/openosp-update.sh $2 $3
        ;;
    health)
        docker-compose -f docker-compose.admin.yml run health
        ;;
    *)
        usage
        ;;
esac
